name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                python-version: 3.8
            - uses: abatilo/actions-poetry@v1.5.0
            - run: poetry run black . --check
